Added support for OpenDistro in integration tests
Bit-Quill/opensearch-net pull request #5
Opened 2022-03-22 04:03 UTC by Yury-Fridlyand

Added support to run integration tests on `OpenDistro` and even on `Elasticsearch`.
Command line sample is:
```bash
./build.sh integrate opendistro-latest writable random:test_only_one --report
```
Used abstractions library update is able to run tests on `OpenDistro` versions `1.13.0-1.13.3` (`opendistro-latest` resolved as `1.13.3`) and `Elasticsearch` `7.10.2` (`elasticsearch-latest` resolved as `7.10.2`). Other versions are incompatible with OpenSearch, so are not supported by the test framework as well.

## Notes
* 3a9fcdf required to run integration tests.
* `latest` resolution for `OpenSearch` is not implemented yet.
* `OpenSearch` is shipped as tarball for Linux only, testing `OpenDistro` and `Elasticsearch` on Windows might fail, because it not supported [yet].

2022-03-22 17:45 UTC, guiangumpac commented on tests/Tests.Core/Extensions/EphemeralClusterExtensions.cs
> +				//if (cluster.ClusterConfiguration.EnableSecurity && notAlreadyAuthenticated)
Should this be removed?

2022-03-22 17:53 UTC, alexmeizer requested changes
Additionally, get in the habit of adding new lines at end of files if you see it missing one and you're touching it. See: https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-03-22 17:53 UTC, alexmeizer commented on tests/Tests.Core/Extensions/EphemeralClusterExtensions.cs
> +				//	settings = settings.BasicAuthentication(ClusterAuthentication.Admin.Username, ClusterAuthentication.Admin.Password);
remove commented code here

2022-03-23 20:33 UTC, alexmeizer approved these changes

2022-03-23 20:39 UTC, Yury-Fridlyand commented on tests/Tests.Core/Extensions/EphemeralClusterExtensions.cs
> +				//	settings = settings.BasicAuthentication(ClusterAuthentication.Admin.Username, ClusterAuthentication.Admin.Password);
Thank you, fixed in 2982ff909.

2022-03-23 20:39 UTC, Yury-Fridlyand commented on tests/Tests.Core/Extensions/EphemeralClusterExtensions.cs
> +				//if (cluster.ClusterConfiguration.EnableSecurity && notAlreadyAuthenticated)
Thank you, fixed in 2982ff909.

2022-03-23 20:45 UTC, ghost approved these changes

2022-03-23 21:37 UTC, MaxKsyunz approved these changes

2022-03-23 23:18 UTC, merged